# Generated by Django 3.2.12 on 2022-05-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizplay',
            old_name='curretn',
            new_name='current',
        ),
        migrations.RemoveField(
            model_name='quizplay',
            name='correct',
        ),
    ]
