# Generated by Django 3.2.12 on 2022-05-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('quizzes', '0004_auto_20220524_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizplay',
            name='results',
        ),
        migrations.AddField(
            model_name='quizplay',
            name='choice_list',
            field=models.ManyToManyField(related_name='choices', to='movies.Movie'),
        ),
    ]
