# Generated by Django 3.2.12 on 2022-05-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quizplay_result_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizplay',
            name='result_list',
        ),
        migrations.AddField(
            model_name='quizplay',
            name='result_list',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
